[907] https://leetcode.com/problems/sum-of-subarray-minimums/discuss/178876/stack-solution-with-very-detailed-explanation-step-by-step


/*
NEXT GREATER ELEMENT
PREV GREATER ELEMENT

NEXT LESS ELEMENT
PREV LESS ELEMENT

907. Sum of Subarray Minimums
2104. Sum of Subarray Ranges

_________________________________________
654. Maximum Binary Tree                |
388. Longest Absolute File Path         |
________________________________________|

*/

